/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bor' at '12/4/18 11:04 AM' with Gradle 2.10
 *
 * @author bor, @date 12/4/18 11:04 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
